### ISSUE TITLE
[MONTHLY]: July - steering committee meeting

### ISSUE THREAD

**Issue by trallard** [numfocus/DISC-committee#12]
## Before the meeting

- [x] Set agenda
- [x] Circulate agenda with all the committee members

## After the meeting

- [x] Review the meeting minutes
- [x] Create public minutes in the `./committee/public-meeting-minutes` folder
- [x] Open PR and Circulate with members for approval
- [x] Merge PR and publish to the <disc@numfocus.org> Google group

**Comment by Ruv7** [comment]
Hi there - unfortunately I missed the last meeting due to unforeseen travel circumstances and I was hoping to catch up by reading the minutes from the meeting. Can you guide me on the best way to do that? I am not super familiar with GitHub as it's not a part of my daily workflow. Also if more time is needed - no rush please share when you're able.

**Comment by mikofski** [comment]
Hi @Ruv7 I haven't transcribed them yet, but they are loosely scribbled in the agenda [here](https://docs.google.com/document/d/1a1MzbtbEWu0rvZbrRTFUd3xXuFzD-cFOroqug5gzQWM/edit#heading=h.dpprkmk9d47t).

**Comment by Ruv7** [comment]
Excellent, thanks!

**Comment by mikofski** [comment]
addressed in #15 -- @trallard I don't have to disc numfocus google group.
